src/core/client.rs
src/core/gcc.rs
src/core/global.rs
src/core/mcs.rs

Register and join channels during MCS connection. Let the caller deal
with message routing. Also, move event conversion for global channel
from `client::Client` into `From` traits.

mcs: add support for additional static channels

---

src/core/client.rs
src/core/sec.rs

For some reason I can't assign you as reviewers here: @fspmarshall, @xacrimon

Expose additional InfoFlags in sec::connect

---

src/core/x224.rs
src/model/error.rs

Instead of emitting an identical error message for all protocol
negotiation failures, consult the failure code field of the message
and use it to generate a better error.
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/1b3920e7-0116-4345-bc45-f2c4ad012761

Include a detailed error for RDP negotiation failures

---

src/core/client.rs
src/core/gcc.rs
src/core/mcs.rs
src/core/sec.rs

Include support for the `performanceFlags` and `connectionType` as part of connection establishment.

Expose additional RDP flags

---

src/core/mcs.rs
src/model/error.rs

In https://github.com/gravitational/rdp-rs/commit/a890091a4e86ec804dfad19fdc2ccb56ae4003f8 we made the static channels a `&[&str]` because at the time, the static channels we needed were always known at compile time, so there was no need for heap allocations.
Since then, we've implemented clipboard sharing, which adds a new static channel that is optionally opened at **runtime** (based on RBAC), so we need to go back to the previous approach.

Revert static channels type change

---

Cargo.toml
src/lib.rs
src/model/error.rs
src/model/link.rs
src/nla/cssp.rs

Swaps native-tls library with rustls.
It indirectly removes the OpenSSL dependency.

Swap native-tls library with rustls

---

src/core/event.rs
src/core/global.rs

It turns out that negative scroll requires that we send the 9-bit two's complement of the delta (seen in FreeRDP [here](https://github.com/FreeRDP/FreeRDP/blob/511444a65e7aa2f537c5e531fa68157a50c1bd4d/client/common/client.c#L1071) and [here](https://github.com/FreeRDP/FreeRDP/blob/511444a65e7aa2f537c5e531fa68157a50c1bd4d/client/Wayland/wlf_input.c#L229)).
Relates to https://github.com/gravitational/teleport/issues/13690, which can be considered fixed once this is merged and the following `teleport` branches are updated with the new HEAD ref of this repo's `master` branch:
- `master`: TODO(link the PR)
- `branch/v10`: TODO(link the PR)
- `branch/v9`: TODO(link the PR)
Double check the [`Verify user input`](https://github.com/gravitational/teleport/blob/9c89af8d2d6d414e0e50693753cbed10b4a56f …

Fix scroll wheel delta

---

src/model/error.rs

Adds a `From` trait implementation that's helpful for the directory sharing implementation

Add `From<std::num::TryFromIntError>`

---

src/core/global.rs

This gets rid of the pesky log message:
```
GLOBAL: Unknown Fast Path order RdpError(RdpError { kind: NotImplemented, message: "GLOBAL: Fast Path parsing not implemented FastpathUpdatetypePtrDefault" })
```

Add fastpath handling for FastpathUpdatetypePtrDefault

---

Cargo.toml
src/core/license.rs
src/core/sec.rs
src/lib.rs
src/model/link.rs
src/nla/cssp.rs

Partially implement `[MS-RDPELE] Remote Desktop Protocol: Licensing Extension`
Implements the `New License Flow`, but omits the `Upgrade License Flow` since we do not support license storage on the client side.

Add RDP Licensing Extension

---

src/core/global.rs

Since this library is a basic implementation of RDP, it lacks
support for a number of advanced server capabilites.
Suppress the global log output for capabilities we don't support,
this is expected.

Ignore unknown server capabilities

---

Cargo.toml
src/lib.rs
src/model/error.rs
src/model/link.rs
src/model/mod.rs
src/model/tls/default.rs
src/model/tls/fips.rs
src/model/tls/mod.rs
src/nla/cssp.rs

It's the first step to make Teleport's Desktop Access FIPS compatibile: https://github.com/gravitational/teleport/issues/9987

Add optional FIPS feature and use BoringSSL with FIPS enabled for TLS connections

---

src/core/global.rs

Solves for part of gravitational/teleport#14451
When we receive the `SetErrorInfoPdu` we now store the value on the client, allowing us to later retrieve a corresponding string value for the error code.
See https://github.com/gravitational/teleport/pull/18959 for how this value is used to display a more descriptive error message to the user.

Add server disconnect error code

---

src/core/gcc.rs
src/core/global.rs
src/core/mcs.rs
src/core/sec.rs

- Adds more specificity for detecting the RDP version in `pub enum Version`
- Fixes a bug in `impl From<u32> for Version`
- Fixes a bug in `rdp_extended_infos` which was preventing us from being able to send performance flags
- Request 16bpp explicitly rather than requesting 24bpp but also saying we only support 16bpp or 32bpp

Fix `performanceFlags` and make 16bpp explicit

---

src/codec/rle.rs
src/core/capability.rs

The existing code for this was a direct port of C code. As a result, it had a bunch of variables with scope larger than necessary and no documentation.
No functional changes here, just simplify the code and add comments and links to the relevant parts of the spec to make things easier to understand.
Included a new test to verify that behavior is the same before and after the change.

Clean up 32bpp RLE decoder

---

src/core/capability.rs

Fixes a regression in 112475c. These components that look like maps are actually ordered, and that commit broke serialization by changing the order of fields.

Fix connection establishment

---

src/core/client.rs
src/core/tpkt.rs
src/model/link.rs

Some of the documentation tests were using methods behind the integration feature, which was not enabled, prevenging the examples from compiling.

Fix cargo test

---

src/core/client.rs
src/core/event.rs
src/core/global.rs

This is used to synchronize the state of the toggle keys (like caps lock), as well as to reset the server state to "all keys up."

Add support for the TS_SYNC_EVENT

---

Cargo.toml

Needed for clang / cmake build fixes.

Upgrade `boring` from v3.1.0 to v4.3.0

---

Cargo.toml
src/core/license.rs
src/core/mcs.rs
src/core/tpkt.rs
src/core/x224.rs
src/model/data.rs
src/model/error.rs
src/model/unicode.rs
src/nla/asn1.rs
src/nla/ntlm.rs

Our current implementation of MS-RDPELE is insufficient. We'll need to add hooks for client-side license storage, but before we can do that we need to parse additional metadata from the licensing PDUs.

Enhance MS-RDPELE support
